### PR TITLE
use `.` in `any_vars()`

### PR DESCRIPTION
**Pull request by romainfrancois**
This passes check() against dplyr 0.8.0 which is about to be released. The changes are minimal and I guess this chunk below that is repeated many times could go into its own function: 

```r
# Discarding unusable observations ----------------------------------------
  d <- data %>%
    filter_at(vars(!!sym(distance)), any_vars(. > 0)) %>%
    filter_at(vars(!!sym(distance)), any_vars(is.finite(.))) %>%
    filter_at(vars(!!sym(dependent_variable)), any_vars(. > 0)) %>%
    filter_at(vars(!!sym(dependent_variable)), any_vars(is.finite(.)))
```

Something like this (untested): 

```r
usable <- function(x) x > 0 & is.finite(x)

discard_unusable <- function(data, ...){
  data %>%
    filter_at( vars(...), all_vars(usable)) 
}
discard_unusable(d, distance, dependent_variable)
```

### CODE REVIEW

**Comment by pachadotdev** [comment]
Thanks a lot @romainfrancois !!!! it makes perfect sense. I am against "." but I see a very clear use here :)

**Comment by romainfrancois** [comment]
The suggestion above with `discard_unusable()` does not use `.`, but if you are going to use `filter_*()` then you need `.` there is no real way around it.  Although similarly this code: 

```r
d <- data %>%
    filter_at(vars(!!sym(distance)), any_vars(. > 0))
```

could equally be: 

```r
d <- data %>%
    filter(!!sym(distance) > 0))
```

as there's only one variable involved, you don't really need `filter_at()`

**Comment by pachadotdev** [comment]
thanks again, at some point vanilla filter returned some warnings and we went for the long version
I'll add the function you suggestf

**Comment by pachadotdev** [comment]
@romainfrancois now that I'm doing changes, what do you think about including some `pkgdown` alike messages with the spinning \ | \ / and all of that?

**Comment by romainfrancois** [comment]
I don't know what you mean by `the spinning \ | \ / and all of that` 😬

**Comment by pachadotdev** [comment]
when you run `pkgdown::build_site()` it shows some cool messages like this:
```
══ Building pkgdown site ═══════════════════════════════════════════════════════════════════════════════════════════════
Reading from: '/home/pacha/github/gravity'
Writing to:   '/home/pacha/github/gravity/docs'
── Initialising site ───────────────────────────────────────────────────────────────────────────────────────────────────
── Building home ───────────────────────────────────────────────────────────────────────────────────────────────────────
Reading 'README.Rmd'
Writing 'index.html'
```

and it also shows a symbol that spins while running

**Pull request merged**
